# Generated by Django 5.0.6 on 2024-05-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tanmirtpost_latitude_tanmirtpost_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanmirtpost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tanmirtpost',
            name='longitude',
        ),
    ]
