# Generated by Django 5.0.6 on 2024-05-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tanmirtpost_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanmirtpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanmirtpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
