# Generated by Django 5.0.6 on 2024-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tanmirtpost_latitude_tanmirtpost_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanmirtpost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tanmirtpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
