# Generated by Django 5.0.6 on 2024-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanmirtpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
